# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- script: |
    echo 'Current directory is '
    pwd
    echo 'Current OS is 1) '
    system_profiler SPSoftwareDataType
    echo 'Current OS is 2) '
    sw_vers
  displayName: '<<<START>>>'

- script: |
    echo '-------------------------'
    pwd
    echo 'Listing current directory '
    ls -la
    echo '-------------------------'
    echo 'Listing parent directory '
    cd ..
    pwd
    ls -la
    echo '-------------------------'
    echo 'Listing parent directory '
    cd ..
    pwd
    ls -la
    echo '-------------------------'
    echo 'Listing parent directory '
    cd ..
    pwd
    ls -la
    echo '-------------------------'
    displayName: '<<<Directory info>>'
    
- script: |
    echo '-------------------------'
    xcode-select --version
    echo '-------------------------'
    displayName: '<<<Directory info>>'
    
- script: |
    echo '-------------------------'
    echo '-------------------------'
    echo '-------------------------'
    

- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphoneos13.1'
    packageApp: true
    archivePath: 'TEST.xarchive'
    signingOption: 'auto'
    teamId: '7X9ME2T5WH'