# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- script: |
    echo '-------------------------'
    echo '-------------------------'
    echo '-------------------------'
    displayName: 'Step 1'
    
- script: |
    echo '-------------------------'
    xcode-select --version
    echo '-------------------------'
    displayName: 'Step 2'
    
- script: |
    echo '-------------------------'
    xcode
    echo '-------------------------'
    displayName: 'Step 3'
    
- script: |
    echo '-------------------------'
    /Developer/usr/bin/xcodebuild -version
    echo '-------------------------'
    displayName: 'Step 4'
    
- script: |
    echo '-------------------------'
    cd ~/
    ls -la
    echo '-------------------------'
    displayName: 'Step 4'
    
- script: |
    echo '-------------------------'
    echo '-------------------------'
    echo '-------------------------'
    displayName: 'Step 6'
    

#- task: Xcode@5
#  inputs:
#    actions: 'build'
#    sdk: 'iphoneos13.1'
#    packageApp: true
#    archivePath: 'TEST.xarchive'
#    signingOption: 'auto'
#    teamId: '7X9ME2T5WH'